### PR TITLE
Ot base implementation from Chou Orlandi with fixes

### LINKED ISSUE #388: HL17 baseOt implementation
Naor Pinkas is not the fastest base OT. 
By changing the protocol to [HL17 ](https://eprint.iacr.org/2017/1011) we can cut speedup the offline phase. (From 31 to 17 seconds in my tests, when using BigInteger). (In the case of Spdz with Mascot)
The HL17 is based on ChouOrland OT

### PR DESCRIPTION
**Pull request by Gugi264**
Closes #388

### CODE REVIEW

**Comment by jot2re** [comment]
As discussed in the comments on issue #388 I unfortunately have to reject the PR.

**Comment by jot2re** [comment]
After more discussion with Claudio Orlandi, I realised that the amount of changes to make the protocol secure are really minimal. Thus I think it still makes sense to merge it.
I am really sorry for being too quick to reject the PR previously. 
I understand that you probably don't have time to implement the suggestions at this point. If not, I will probably just do it myself.

**Comment by Gugi264** [comment]
Hi, what are the necessary changes? If they are really only small I can implement them.

**Comment by Gugi264** [comment]
Ok :)

**Comment by jot2re** [comment]
@quacktiamauct can you implement the changes I have requested?

File: tools/ot/src/main/java/dk/alexandra/fresco/tools/ot/base/AbstractChouOrlandiOT.java [hunk 1]
```diff
@@ -94,27 +95,24 @@ public StrictBitVector receive(boolean choiceBit) {
...
+        T U;
         if (choiceBit == false) {
-            R = T.exponentiation(BigInteger.ZERO).groupOp(getGenerator().exponentiation(x));
+            U = A.exponentiation(BigInteger.ZERO).groupOp(getGenerator().exponentiation(x));
         } else {
-            R = T.exponentiation(BigInteger.ONE).groupOp(getGenerator().exponentiation(x));
+            U = A.exponentiation(BigInteger.ONE).groupOp(getGenerator().exponentiation(x));
         }
-        network.send(otherId, R.toByteArray());
+        network.send(otherId, U.toByteArray());
```
Comment (jot2re) [inline tools/ot/src/main/java/dk/alexandra/fresco/tools/ot/base/AbstractChouOrlandiOT.java:110]: We still need to ensure that `toByteArray` always returns an array of the same amount of bytes regardless of the size of the underlying element. If not and `toByteArray` returns things as big endian we end up in situation where two different values will have the same byte representation.

File: tools/ot/src/main/java/dk/alexandra/fresco/tools/ot/base/ECNaorPinkasOt.java [hunk 2]
```diff
@@ -0,0 +1,126 @@
...
+    int bytesNeeded = (2 * curve.getFieldSize()+7) / 8;
+    byte[] nextInt = new byte[bytesNeeded];
+    rand.nextBytes(nextInt);
+    BigInteger rawInt = new BigInteger(1, nextInt);
+    return curve.fromBigInteger(rawInt.mod(curve.getField().getCharacteristic()));
+  }
+
+  @Override
+  BouncyCastleECCElement decodeElement(byte[] bytes) {
+    return new BouncyCastleECCElement(this.curve.decodePoint(bytes));
```
Comment (jot2re) [inline tools/ot/src/main/java/dk/alexandra/fresco/tools/ot/base/ECNaorPinkasOt.java]: Ensure that the element is of the correct order (when the curve does not have cofactor 1). I.e. that the point is actually valid and that the point multiplied by the cofactor is different from the point at infinity.
It might also be relevant to check that it is not on the point of infinity.

File: tools/ot/src/main/java/dk/alexandra/fresco/tools/ot/base/AbstractChouOrlandiOT.java [hunk 3]
```diff
@@ -128,28 +126,22 @@ private byte[] receiveRandomOt(boolean choiceBit) {
...
         k0Hash = hashDigest.digest();
 
-        hashDigest.update(S.toByteArray());
-        hashDigest.update(R.toByteArray());
-        // R^y*T^(-jy) with j = 1:
-        // R^y * T^(-1y) == (R + (-T)) * y
-        hashDigest.update((R.groupOp(T.inverse())).exponentiation(y).toByteArray());
+        hashDigest.update(A.toByteArray());
+        // (U * B^(-1))^y
+        hashDigest.update((U.groupOp(A.inverse())).exponentiation(y).toByteArray());
```
Comment (jot2re) [inline tools/ot/src/main/java/dk/alexandra/fresco/tools/ot/base/AbstractChouOrlandiOT.java:144]: In the following SHAKE is used.
Why use both SHA256 and SHAKE? Would it not make sense to use the same hash function?

File: tools/ot/src/main/java/dk/alexandra/fresco/tools/ot/base/ECNaorPinkasOt.java (hunk 2 above)
Comment (jot2re) [reply tools/ot/src/main/java/dk/alexandra/fresco/tools/ot/base/ECNaorPinkasOt.java]: This is also an issue in `ECChouOrlandi` when decoding

**Review by jot2re — CHANGES_REQUESTED** [review]
There are still a lot of security issues from the previous review that has not been addressed. 
I have fixed some of them and explicitly written down the remaining issues and how to fix them

**Comment by Quacktiamauct** [comment]
Fixed in https://github.com/aicis/fresco/pull/389/commits/2ce267e45e817b797bdeff2599c5c20f5de294c6

File: tools/ot/src/main/java/dk/alexandra/fresco/tools/ot/base/AbstractChouOrlandiOT.java (hunk 1 above)
Comment (Quacktiamauct) [reply tools/ot/src/main/java/dk/alexandra/fresco/tools/ot/base/AbstractChouOrlandiOT.java:110]: The underlying BigInteger implementation always returns a big endian representation. The EC implementation an encoded non-compressed point. The first one has no guarantees in the term of byte length, but the second will depend directly on the field size. However I am not quite sure how a variable byte length would be a problem? In any case should we then pad the sent bytes?

File: tools/ot/src/main/java/dk/alexandra/fresco/tools/ot/base/ECNaorPinkasOt.java (hunk 2 above)
Comment (Quacktiamauct) [reply tools/ot/src/main/java/dk/alexandra/fresco/tools/ot/base/ECNaorPinkasOt.java]: BouncyCastle already validates points when decoding, both that they are on the curve and that the order time.
It runs the following:
```java
    protected boolean satisfiesOrder()
    {
        if (ECConstants.ONE.equals(curve.getCofactor()))
        {
            return true;
        }

        BigInteger n = curve.getOrder();

        // TODO Require order to be available for all curves

        return n == null || ECAlgorithms.referenceMultiply(this, n).isInfinity();
    }
```
from `org.bouncycastle.math.ec.ECPoint`

File: tools/ot/src/main/java/dk/alexandra/fresco/tools/ot/base/AbstractChouOrlandiOT.java (hunk 3 above)
Comment (Quacktiamauct) [reply tools/ot/src/main/java/dk/alexandra/fresco/tools/ot/base/AbstractChouOrlandiOT.java:144]: I'm not sure I am following, the later `hashToFieldElement` which uses SHAKE is never called, and the highlighted code only uses SHA-256 for hashing?

File: tools/ot/src/main/java/dk/alexandra/fresco/tools/ot/base/AbstractChouOrlandiOT.java [hunk 4]
```diff
@@ -0,0 +1,187 @@
...
+import java.security.MessageDigest;
+
+import static org.bouncycastle.pqc.math.linearalgebra.BigEndianConversions.I2OSP;
+
+/**
+ * Uses Chou-Orlandi with fixes as seen in https://eprint.iacr.org/2017/1011
+ */
+public abstract class AbstractChouOrlandiOT<T extends InterfaceOtElement<T>> implements Ot {
+
+    private static final String HASH_ALGORITHM = "SHA-256";
```
[the remark this answers is not in the document]
Comment (Quacktiamauct) [reply tools/ot/src/main/java/dk/alexandra/fresco/tools/ot/base/AbstractChouOrlandiOT.java]: Solved in 0c254516f

File: demos/distance/src/test/java/dk/alexandra/fresco/demo/TestDistanceDemo.java [hunk 5]
```diff
@@ -128,7 +128,7 @@ public void testDistanceFromCmdLine3Party() throws Exception {
       try {
         DistanceDemo.main(
             new String[]{"-i", "1", "-p", "1:localhost:8081", "-p", "2:localhost:8082",
-                "-p", "3:localhost:8083", "-s", "dummyArithmetic", "-x", "10", "-y", "10"});
+                "-p", "3:localhost:8083", "-s", "spdz", "-x", "10", "-y", "10"});
```
[the remark this answers is not in the document]
Comment (Quacktiamauct) [reply demos/distance/src/test/java/dk/alexandra/fresco/demo/TestDistanceDemo.java]: Solved in 4fb38fa142f7e4ed5679bd3fba59a720b0956e28

File: tools/ot/src/main/java/dk/alexandra/fresco/tools/ot/base/AbstractChouOrlandiOT.java [hunk 6]
```diff
@@ -0,0 +1,187 @@
...
+     * @return The two random messages sent by the sender.
+     */
+    private Pair<byte[], byte[]> sendRandomOt() {
+        // y
+        BigInteger y = randNum.nextBigInteger(getDhModulus());
+        // S
+        T S = this.getGenerator().exponentiation(y);
+        network.send(otherId, S.toByteArray());
+        // T = G(S)
+        T T = hashToFieldElement(S, "FRESCO|ChouOrlandi|OT");
```
[the remark this answers is not in the document]
Comment (Quacktiamauct) [reply tools/ot/src/main/java/dk/alexandra/fresco/tools/ot/base/AbstractChouOrlandiOT.java]: Fixed in 4733c6681ff9b17a9080b8d278c2e914c08e553d

File: tools/ot/src/main/java/dk/alexandra/fresco/tools/ot/base/BouncyCastleChouOrlandi.java [hunk 7]
```diff
@@ -0,0 +1,55 @@
...
+        Security.addProvider(new BouncyCastleProvider());
+        X9ECParameters ecP = CustomNamedCurves.getByName("curve25519");
+        this.curve = ecP.getCurve();
+        this.dhModulus = curve.getOrder();
+        this.dhGenerator = ecP.getG();
+    }
+
+    @Override
+    BouncyCastleECCElement decodeElement(byte[] bytes) {
+        return new BouncyCastleECCElement(this.curve.decodePoint(bytes));
```
[the remark this answers is not in the document]
Comment (Quacktiamauct) [reply tools/ot/src/main/java/dk/alexandra/fresco/tools/ot/base/BouncyCastleChouOrlandi.java]: BC does both of these, except the infinity check.

File: tools/ot/src/main/java/dk/alexandra/fresco/tools/ot/base/AbstractChouOrlandiOT.java [hunk 8]
```diff
@@ -0,0 +1,187 @@
...
+        if (choiceBit == false) {
+            R = T.exponentiation(BigInteger.ZERO).groupOp(getGenerator().exponentiation(x));
+        } else {
+            R = T.exponentiation(BigInteger.ONE).groupOp(getGenerator().exponentiation(x));
+        }
+        network.send(otherId, R.toByteArray());
+
+        // k = H(S, R, S^x)
+        byte[] key;
+        hashDigest.update(S.toByteArray());
```
[the remark this answers is not in the document]
Comment (Quacktiamauct) [reply tools/ot/src/main/java/dk/alexandra/fresco/tools/ot/base/AbstractChouOrlandiOT.java]: I'm not sure I understand by hashing locally?

[the remark this answers is not in the document]
Comment (jot2re) [reply tools/ot/src/main/java/dk/alexandra/fresco/tools/ot/base/AbstractChouOrlandiOT.java]: Sorry, badly written from my side. The we need to ensure that what gets returned by `toByteArray` is always the same amount of bytes, regardless of the magnitude of the number it represents. Since it is most likely big endian this is a problem, and thus the returned value need to be prepended by empty bytes if S is not a number that is large enough to use the maximum amount of bytes

File: tools/ot/src/main/java/dk/alexandra/fresco/tools/ot/base/AbstractChouOrlandiOT.java [hunk 9]
```diff
@@ -0,0 +1,187 @@
...
+        T S = this.decodeElement(network.receive(otherId));
+        // T = G(S)
+        T T = hashToFieldElement(S, "FRESCO|ChouOrlandi|OT");
+        // R = T^c*g^x
+        // if c = 0 -> R = g^x
+        // if c = 1 -> R = T*g^x
+        BigInteger x = randNum.nextBigInteger(getDhModulus());
+        T R;
+        if (choiceBit == false) {
+            R = T.exponentiation(BigInteger.ZERO).groupOp(getGenerator().exponentiation(x));
```
[the remark this answers is not in the document]
Comment (jot2re) [reply tools/ot/src/main/java/dk/alexandra/fresco/tools/ot/base/AbstractChouOrlandiOT.java]: Yes, we currently don't care about timing attacks. In particular since the code is Java which is naturally vulnerable to such things

File: tools/ot/src/main/java/dk/alexandra/fresco/tools/ot/base/BouncyCastleChouOrlandi.java (hunk 7 above)
[the remark this answers is not in the document]
Comment (jot2re) [reply tools/ot/src/main/java/dk/alexandra/fresco/tools/ot/base/BouncyCastleChouOrlandi.java]: Either also validate manually or write a comment that it is expected from the library. It is not given that such things are validated when decoding a point and we cannot be sure bouncy castle does not change this functionality in the future. A redundant check is always better than a missing check

File: tools/ot/src/main/java/dk/alexandra/fresco/tools/ot/base/AbstractChouOrlandiOT.java (hunk 1 above)
Comment (jot2re) [reply tools/ot/src/main/java/dk/alexandra/fresco/tools/ot/base/AbstractChouOrlandiOT.java:114]: Yes, padding should be added to ensuring equal byte length for all numbers

File: tools/ot/src/main/java/dk/alexandra/fresco/tools/ot/base/ECNaorPinkasOt.java (hunk 2 above)
Comment (jot2re) [reply tools/ot/src/main/java/dk/alexandra/fresco/tools/ot/base/ECNaorPinkasOt.java]: As mentioned above ideally manually check this as well or write a comment that it is expected from the library. But the functionality in the library might change, hence it is better to also check it manually since this can _completely_ unmine the security if not done

File: tools/ot/src/main/java/dk/alexandra/fresco/tools/ot/base/AbstractChouOrlandiOT.java (hunk 3 above)
Comment (jot2re) [reply tools/ot/src/main/java/dk/alexandra/fresco/tools/ot/base/AbstractChouOrlandiOT.java]: If SHAKE is never used then the code should be removed. Currently there is code using both kinds, but if the SHAKE code is now dead it should just be removed

Comment (Quacktiamauct) [reply tools/ot/src/main/java/dk/alexandra/fresco/tools/ot/base/AbstractChouOrlandiOT.java]: Resolved by 600750daa

File: tools/ot/src/main/java/dk/alexandra/fresco/tools/ot/base/AbstractChouOrlandiOT.java (hunk 1 above)
Comment (Quacktiamauct) [reply tools/ot/src/main/java/dk/alexandra/fresco/tools/ot/base/AbstractChouOrlandiOT.java:114]: Actually, I'm not sure this is a problem since the byte-representation is prepended with the sign in the first byte.

File: tools/ot/src/main/java/dk/alexandra/fresco/tools/ot/base/AbstractChouOrlandiOT.java (hunk 3 above)
Comment (Quacktiamauct) [reply tools/ot/src/main/java/dk/alexandra/fresco/tools/ot/base/AbstractChouOrlandiOT.java]: Solved by 20615343b

File: tools/ot/src/main/java/dk/alexandra/fresco/tools/ot/base/AbstractChouOrlandiOT.java (hunk 1 above)
Comment (jot2re) [reply tools/ot/src/main/java/dk/alexandra/fresco/tools/ot/base/AbstractChouOrlandiOT.java:101]: You are right that for network communication it does not matter how many bytes is used.
However when we need to use the result we can get into issues if we  have a number that is represented using a 31 byte big endian integer, and we need to hash this. Thus a bunch of 0-bytes gets appended. Now the result will represent a much larger number than it actually is. In that case the number should be prepended with 0-bytes to ensure consistent encoding once it gets mapped to a 32 byte array (or something larger)

File: tools/ot/src/main/java/dk/alexandra/fresco/tools/ot/base/ECNaorPinkasOt.java (hunk 2 above)
Comment (Quacktiamauct) [reply tools/ot/src/main/java/dk/alexandra/fresco/tools/ot/base/ECNaorPinkasOt.java]: Added a comment in 0375fd3

File: tools/ot/src/main/java/dk/alexandra/fresco/tools/ot/base/AbstractChouOrlandiOT.java (hunk 8 above)
[the remark this answers is not in the document]
Comment (Quacktiamauct) [reply tools/ot/src/main/java/dk/alexandra/fresco/tools/ot/base/AbstractChouOrlandiOT.java]: Solved by 0375fd3

File: tools/ot/src/main/java/dk/alexandra/fresco/tools/ot/base/AbstractChouOrlandiOT.java (hunk 1 above)
Comment (Quacktiamauct) [reply tools/ot/src/main/java/dk/alexandra/fresco/tools/ot/base/AbstractChouOrlandiOT.java:101]: Solved by 0375fd3

**Review by jot2re — CHANGES_REQUESTED** [review]
Look good. I think the only issue is that there is not full coverage with the current tests. If you could add a couple of tests to ensure this (so the CI/CD won't complain once it gets merged) that would be great

**Review by jot2re — APPROVED** [review]
