### PR TITLE
Replace kryo network and fix newly uncovered AsyncNetwork problems

### LINKED ISSUE #281: Replace KryoNet Network with AsyncNetwork
In order to be able to remove KryoNet dependency we need to replace all usage of the KryoNet Network with the new `AsyncNetwork` implementation.

### PR DESCRIPTION
**Pull request by GuutBoy**
This pull request removes and replaces the KryoNet based network implementation. Doing so uncovered some unfortunate behavior in the AsyncNetwork implementation which this PR also fixes and the AsyncNetwork is cleaned up a bit.  

This closes #281

### CODE REVIEW

File: suite/spdz/src/test/java/dk/alexandra/fresco/suite/spdz/TestMaliciousBehaviour.java [hunk 1]
```diff
@@ -52,73 +51,53 @@ public void reset() {
...
-  @Test
-  public void testMaliciousInput() {
+  @Test(expected=MaliciousException.class)
+  public void testMaliciousInput() throws Throwable {
     try {
       runTest(new BasicArithmeticTests.TestInput<>(), EvaluationStrategy.SEQUENTIAL_BATCHED, 2,
           Corrupt.INPUT);
-      Assert.fail("Should not go well");
     } catch (RuntimeException e) {
-      if (e.getCause().getCause() == null || !(e.getCause()
```
Comment (pffrandsen) [inline suite/spdz/src/test/java/dk/alexandra/fresco/suite/spdz/TestMaliciousBehaviour.java]: though prettier, does not have a the same sematic

File: tools/ot/src/test/java/dk/alexandra/fresco/tools/ot/otextension/CheatingNetwork.java [hunk 2]
```diff
@@ -1,27 +1,31 @@
...
+  private final CloseableNetwork network;
+
   private int cheatByteNo;
   private int messageNo;
   private int counter = 0;
   private boolean cheat = false;
 
   public CheatingNetwork(NetworkConfiguration conf) {
-    super(conf);
+    this.network = new AsyncNetwork(conf);
```
Comment (pffrandsen) [inline tools/ot/src/test/java/dk/alexandra/fresco/tools/ot/otextension/CheatingNetwork.java]: Since it now has become a decorator, then call the network decorated or delegate

File: core/src/main/java/dk/alexandra/fresco/framework/network/async/AsyncNetwork.java [hunk 3]
```diff
@@ -26,7 +28,6 @@
 import java.util.concurrent.TimeUnit;
 import java.util.concurrent.TimeoutException;
 import java.util.concurrent.atomic.AtomicBoolean;
-import java.util.stream.Collectors;
 import org.slf4j.Logger;
 import org.slf4j.LoggerFactory;
```
Comment (pffrandsen) [inline core/src/main/java/dk/alexandra/fresco/framework/network/async/AsyncNetwork.java]: This class is now the only implementation of network, move it to the network package instead of ...async

File: suite/spdz/src/test/java/dk/alexandra/fresco/suite/spdz/TestMaliciousBehaviour.java (hunk 1 above)
Comment (GuutBoy) [reply suite/spdz/src/test/java/dk/alexandra/fresco/suite/spdz/TestMaliciousBehaviour.java]: True, but the test will fail/pass on the same cases. And it is much more clear what we are testing for now.

File: tools/ot/src/test/java/dk/alexandra/fresco/tools/ot/otextension/CheatingNetwork.java (hunk 2 above)
Comment (GuutBoy) [reply tools/ot/src/test/java/dk/alexandra/fresco/tools/ot/otextension/CheatingNetwork.java]: Good point ... in fact, think to should not even be dependent on AsyncNetwork. We could use any closeable network here.

File: suite/spdz/src/test/java/dk/alexandra/fresco/suite/spdz/TestMaliciousBehaviour.java (hunk 1 above)
Comment (pffrandsen) [reply suite/spdz/src/test/java/dk/alexandra/fresco/suite/spdz/TestMaliciousBehaviour.java]: If the latter statement was true, then the emantic is identical. Which it is not. Call me for explanation.

As I said, it is prettier so this is just a comment. Do not change anything

**Comment by GuutBoy** [comment]
@pffrandsen if you have ideas on how to make it better/more failsafe, I would be happy to know and update it again. 

IMO the main gain of this implementation is to have a simple implementation that we understand well, making it easier to fix bugs or adjust the implementation we want/need. So as long at it is otherwise not considerably worse than the KryoNet based implementation (which it does not seem to be), I think it is preferable.

**Comment by pffrandsen** [comment]
@GuutBoy It is not because I have ready ideas. My gut feeling is the process has not been adequately controlled in order to produce failsafe code. It does seem like trial and error. Hence my comment. So this remark really is stating: Hmm
