### PR TITLE
Exponentiation bug

### LINKED ISSUE #303: Exponentiation with open exponent fails when exponent is a 2-power
A bug in `ExponentiationOpenExponent.java` means that a `NullPointerException` is thrown when computing exponentiation with an exponent that is a power of 2. 

The problem arises as the `IterationState` object is not initialized properly.

### PR DESCRIPTION
**Pull request by GuutBoy**
Fixes a bug pointed out on gitter where the exponentiation with and open exponent would fail with a `NullPointerException` when the exponent was a power of two. 

This closes #303

### CODE REVIEW

File: core/src/main/java/dk/alexandra/fresco/lib/math/integer/exp/ExponentiationOpenExponent.java [hunk 1]
```diff
@@ -29,7 +36,8 @@ public ExponentiationOpenExponent(DRes<SInt> x, BigInteger e) {
   public DRes<SInt> buildComputation(ProtocolBuilderNumeric builder) {
     return builder.seq((seq) -> {
       DRes<SInt> accEven = base;
-      return new IterationState(exponent, accEven, null);
+      DRes<SInt> accOdd = seq.numeric().known(BigInteger.ONE);
+      return new IterationState(exponent, accEven, accOdd);
```
Comment (pffrandsen) [inline core/src/main/java/dk/alexandra/fresco/lib/math/integer/exp/ExponentiationOpenExponent.java]: This gives quite unnecessary multiplication of known values.

Comment (pffrandsen) [reply core/src/main/java/dk/alexandra/fresco/lib/math/integer/exp/ExponentiationOpenExponent.java]: I redid your solution to save the multiplications

Comment (GuutBoy) [reply core/src/main/java/dk/alexandra/fresco/lib/math/integer/exp/ExponentiationOpenExponent.java]: Yikes, thanks for catching that!
